Repository jemissik/ecodata, pull requests merged in 2023-02, with the labels that each got.

#99 Fix bug where changing apps bleed into each other
  pymovebank/app/__main__.py
  pymovebank/app/apps/gridded_data_explorer_app.py
  pymovebank/app/apps/movie_maker_app.py
  pymovebank/app/apps/subsetter_app.py
  pymovebank/app/apps/tracks_explorer_app.py
  pymovebank/panel_utils.py
Labels: bug

#105 Move requirements from pyproject to dynamic setup.py
  ecodata-env.yml
  pyproject.toml
  setup.py
Labels: package

#113 Add basic tests for apps
  ecodata/tests/conftest.py
  ecodata/tests/test_apps.py
Labels: package

#114 Update docs for multi project setup
  .readthedocs.yaml
  docs/Makefile
  docs/apps/conf.py
  docs/conf.py
  docs/package/conf.py
Labels: documentation
